fixes the grammer
EnterpriseQualityCoding/FizzBuzzEnterpriseEdition pull request #591
Opened 2022-07-16 07:39 UTC by TaAutumn

2022-07-19 16:58 UTC, UriyaHarpeness requested changes
Dis grAmMer. i'sNT evEn GoOdd;

2022-07-19 22:44 UTC, Arsalan-Zahid commented
W

2022-07-19 22:45 UTC, Arsalan-Zahid commented
W autumn

2022-07-20 18:16 UTC, TaAutumn commented
> W autumn

Thainks: )

2023-05-28 02:03 UTC, closed without merging